# Generated by Django 4.0.4 on 2022-05-14 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Worktag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.TextField()),
            ],
            options={
                'unique_together': {('tag_name',)},
            },
        ),
        migrations.CreateModel(
            name='Videomaker',
            fields=[
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('free_status', models.BooleanField(default=True)),
                ('score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='newApp.score')),
                ('work_tag', models.ManyToManyField(blank=True, to='newApp.worktag')),
            ],
            options={
                'verbose_name_plural': 'Videomakers',
            },
        ),
    ]
