# Generated by Django 4.0.4 on 2022-05-16 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0002_alter_videomaker_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomaker',
            name='work_tag',
        ),
        migrations.AddField(
            model_name='videomaker',
            name='work_tag',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='newApp.worktag'),
            preserve_default=False,
        ),
    ]
