# Generated by Django 4.0.4 on 2022-05-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0003_remove_videomaker_work_tag_videomaker_work_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomaker',
            name='experience',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videomaker',
            name='maker_mail',
            field=models.EmailField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videomaker',
            name='phone_number',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
