# Generated by Django 4.0.4 on 2022-05-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0004_videomaker_experience_videomaker_maker_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomaker',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
