# Generated by Django 4.0.4 on 2022-05-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0005_alter_videomaker_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomaker',
            name='experience',
            field=models.CharField(max_length=2),
        ),
    ]
