# Generated by Django 4.0.4 on 2022-05-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0006_alter_videomaker_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videomaker',
            old_name='experience',
            new_name='experience_level',
        ),
    ]
