# Generated by Django 4.0.4 on 2022-06-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0007_rename_experience_videomaker_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomaker',
            name='city',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videomaker',
            name='service_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videomaker',
            name='telegram_link',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_days', models.IntegerField(default=0)),
                ('maker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newApp.videomaker')),
            ],
        ),
    ]
